### ISSUE TITLE
Patch 7.0 Destroyed Cooldown API

### ISSUE THREAD

**Issue by gentmat** [antonpup/Dota2GSI#11]
I noticed that attribute and items .Cooldown doesnt work with patch 7.0 . 
Anyone having this issue ?

**Comment by antonpup** [comment]
Will look into it in the next few days. Anything else get broken with 7.0?

**Comment by antonpup** [comment]
I looked into this. The cooldowns aren't being sent to the library properly. It's always sending 0. It's an issue with Dota 2 and should be reported to Valve if possible.

I also looked into Talents. GSI does send talent information over, however, they are all labeled "attributes" and so due to a limitation in Newtonsoft, it does not allow multiple parameters to have the same name. And so it parses just one talent. I will see if I can find a workaround later for this.

**Comment by gentmat** [comment]
"It's always sending 0" It was always working prior patch 7 .
Maybe they will fix it then i ll update the issue when they do . About the
talent tree (yeah that would be nice)
good job and hope you the best .

**Comment by a10nik** [comment]
Looks like now the game is sending cooldowns properly. 
```
"ability0": {
                        "name": "meepo_earthbind",
                        "level": 1,
                        "can_cast": false,
                        "passive": false,
                        "ability_active": true,
                        "cooldown": 8,
                        "ultimate": false
                },
```
Is the cooldown part of the issue resolved then?

**Comment by gentmat** [comment]
I m not playing from 2 weeks ! hospital :(
I ll check it when i come back into game for sure.
Ty for the update
